### PR TITLE
Removing dead files and old yaml references

### PR DESCRIPTION
**Pull request by marcospb19**
Clap's configuration dead `.yml` files from `chroot`and `nice` were deleted.

Also fixed comments that referenced the old `yaml` usage.

### CODE REVIEW

**Comment by marcospb19** [comment]
Force pushed to add the prefix `Touch: ` to the commit message (now the CI is suffering again with the testing haha I feel bad for them).

**Comment by marcospb19** [comment]
Don't mind the force pushes :D, minor adjustments.

**Comment by GrayJack** [comment]
Thanks for contributing!! :smile: 

Can change the merge to the dev branch? I'm trying to move away from master branch

**Comment by marcospb19** [comment]
Done :+1::+1:.

**Comment by GrayJack** [comment]
Lets try again
bors r+

**Pull request merged**
