### PR TITLE
Implement Clear

### PR DESCRIPTION
**Pull request by Ashwin-A-K**
Address issue #69 

It is just a one-line simple code

### CODE REVIEW

**Comment by GrayJack** [comment]
Can you implement these features too? That would be awesome!!

```
-T TERM     use this instead of $TERM
-x          do not try to clear scrollback
```

Also, use the [git message formatting](https://github.com/GrayJack/coreutils/blob/master/CONTRIBUTING.md#git-commit-messages) for future commits

**Comment by Ashwin-A-K** [comment]
ok... correct me if i am wrong...
-> -x option does the same thing as clear
-> -T $TERM option does clear the screen and lands to the line next to the prompt

**Comment by GrayJack** [comment]
Yes, -x does that, but it allows the person to scroll back

The -T option let you choose a TERM to clear, while absent the utility clears $TERM, that means, the current one

**Comment by Ashwin-A-K** [comment]
ok... And my output was
```
$ clear -x | hexdump -C
00000000  1b 5b 48 1b 5b 32 4a                              |.[H.[2J|
00000007
$ clear | hexdump -C
00000000  1b 5b 33 4a 1b 5b 48 1b  5b 32 4a                 |.[3J.[H.[2J|
0000000b
$ clear -T $TERM | hexdump -C
00000000  1b 5b 33 4a 1b 5b 48 1b  5b 32 4a                 |.[3J.[H.[2J|
0000000b
```

Am i good to go ?

**Comment by GrayJack** [comment]
In that case just implement the `-x`, `-T` could be a feature for the future

**Comment by GrayJack** [comment]
Thanks for the contribution, gonna merge asap

**Pull request merged**
