### PR TITLE
Cut: fixing exit code and error message

### PR DESCRIPTION
**Pull request by mkindahl**
Command `cut` returned zero exit code regardless of successful execution or failure, so fixed that by returning a `Result` type from `main`. Also took the opportunity to fix the error handling since errors are only strings anyway.

### CODE REVIEW

**Comment by GrayJack** [comment]
Can you give me a example where it should error out so I can test it here as well?

Cause what I remember of your code, I think the simple fix would be put a `process::exit(1)` after `eprintln` macro

```rust
    if let Err(err) = result {
        eprintln!("cut: {}", err);
        process::exit(1);
    }
```

**Comment by mkindahl** [comment]
For example `cut -f-` will give an error, or `cut -f5-2`.

Yes, the error code could be fixed that way as well, but since all the errors are printed the same way, there is little point in distinguishing them using an `enum`, so I just cleaned it up into a single error code. If it was a library, the story would be different: then a caller might want to distinguish the different kinds of errors and handle them differently.

**Comment by mkindahl** [comment]
The error message will look different with this change though: is that what you're concerned about?

**Comment by GrayJack** [comment]
Not, I don't mind at all, it was just a commentary, soon as I get home, I'll merge this PR :smile:

**Comment by GrayJack** [comment]
Ok, I'm back home, so, the error returned on your branch is "Error: invalid range with no endpoint"
This should be "cut: invalid range with no endpoint: -", all utils error messages start with the util name

**Comment by mkindahl** [comment]
Fixed. The `Error` is hardcoded and will be possible until they have added the `Termination` trait to standard (it's in nightly right now).

**Pull request merged**
